/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Pojo.Empleado;
import com.google.gson.Gson;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author DewinU
 */
public class DlgReporte extends javax.swing.JDialog {
    List<Empleado> empleados;
    Gson gson;

    /**
     * Creates new form DlgReporte
     * @param parent
     * @param modal
     * @throws java.io.FileNotFoundException
     */
    public DlgReporte(java.awt.Frame parent, boolean modal) throws FileNotFoundException, JRException {
        super(parent, modal);
        gson = new Gson();
        empleados = new ArrayList<>();
        empleados.addAll(Arrays.asList(gson.fromJson(new FileReader(getClass().
                    getResource("/Data/data.json").getPath()), Empleado[].class)));
        initComponents();
        loadReport(empleados,pnlReport);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlReport.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlReport, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 613, 482);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                DlgReporte dialog = new DlgReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(DlgReporte.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(DlgReporte.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    public void loadReport(List<Empleado> empleados, JPanel pnlReport) throws JRException{
        JRBeanCollectionDataSource datasource = 
                new JRBeanCollectionDataSource(empleados);
            Map<String,Object> params = new HashMap<>();
            String rutaReport = getClass().
                getResource("/Reports/EmpleadosReport.jasper").
                getPath();
            JasperPrint jrPrint = JasperFillManager.
                    fillReport(rutaReport, params, datasource);
            pnlReport.add(new JRViewer(jrPrint));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlReport;
    // End of variables declaration//GEN-END:variables
}
