/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.EmpleadoTableModel;
import java.awt.Rectangle;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author DewinU
 */
public class TableFrm extends javax.swing.JFrame {
    
    private EmpleadoTableModel empleadoTb;
    private boolean isNew;
    private boolean isEdit;
    private DlgReporte dlgReport;

    /**
     * Creates new form TableFrm
     */
    public TableFrm() throws FileNotFoundException {
        initComponents();
        empleadoTb = new EmpleadoTableModel();
        empleadoTb.loadFromJson();
        tblEmpleados.setModel(empleadoTb);
        setSelectedRow(0);
        setPreferredWidthColumns(6, 6, 200);
        
    }
    
    public void setSelectedRow(int row) {
        tblEmpleados.getSelectionModel().setSelectionInterval(row, row);
    }

    public void setScrollRectVisible(int row) {
        tblEmpleados.scrollRectToVisible(new Rectangle(tblEmpleados.getCellRect(row, 0, true)));
    }

    private void setPreferredWidthColumns(int start, int end, int width) {
        for (int i = start; i <= end; i++) {
            tblEmpleados.getColumnModel().getColumn(i).setPreferredWidth(width);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollTable = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        pnlReportsButton = new javax.swing.JPanel();
        btnReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        btnNew.setText("Nuevo");
        pnlButtons.add(btnNew);

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSave);

        btnDelete.setText("Eliminar");
        pnlButtons.add(btnDelete);

        getContentPane().add(pnlButtons);

        pnlTable.setLayout(new java.awt.BorderLayout());

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollTable.setViewportView(tblEmpleados);

        pnlTable.add(jScrollTable, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTable);

        btnReports.setText("Reportes!");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        pnlReportsButton.add(btnReports);

        getContentPane().add(pnlReportsButton);

        setBounds(0, 0, 633, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        try {
            // TODO add your handling code here:
            dlgReport = new DlgReporte(this, true);
            dlgReport.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TableFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(TableFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TableFrm().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TableFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlReportsButton;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables
}
